### ISSUE TITLE
Scrollview doesn't scroll....

### ISSUE THREAD

**Issue by fabiosoft** [kronik/DKLiveBlur#10]
I have a custom cell...everything works good except the scrollview inside the cell...it doesn't scroll. 
I tried the build code inside another project (original UITableView) and it scrolls like a charm.
How can i solve?

**Comment by kronik** [comment]
Try to set 'canCancelTouchEvents' to NO (By default it's YES). Or inherit your own tableview/scrollview and override all touch events to pass it further to all other child subviews.
