### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by pepotiger** [kronik/DKLiveBlur#8]
I got an EXC_BAD_ACCESS
while trying to assign an image to originalImage property.

**Comment by kronik** [comment]
Hi, 

Can't repro it. Could you share with your sources?

**Comment by pepotiger** [comment]
Sorry for the late reply.
There is no special configuration, I created a single window application, included the DKLiveBlurView.h/.m and put a background, assigned the scroll view and original image properties, in viewDidLoad and it just crashes!
The following link contains the project you can check it.
https://www.dropbox.com/s/seqaf6vwfc1q8wq/TestingAPp.zip

**Comment by kronik** [comment]
You did it a bit wrong. So just remove LiveBlur view from the storyboard and put following code into your AAViewController viewDidLoad method:

```
DKLiveBlurView *backgroundView = [[DKLiveBlurView alloc] initWithFrame: self.view.bounds];

backgroundView.originalImage = [UIImage imageNamed:@"bg1.jpg"];
backgroundView.scrollView = self.contentV;
backgroundView.isGlassEffectOn = YES;

self.contentV.backgroundView = backgroundView;
```

I've also replaced UIScrollView with UITableView to set backgroundView property. Originally you can add it as an additional view to your UIScrollView element.
